// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/logistic.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentStatus int32

const (
	ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED      ShipmentStatus = 0
	ShipmentStatus_SHIPMENT_STATUS_CREATED          ShipmentStatus = 1
	ShipmentStatus_SHIPMENT_STATUS_PICKED_UP        ShipmentStatus = 2
	ShipmentStatus_SHIPMENT_STATUS_IN_TRANSIT       ShipmentStatus = 3
	ShipmentStatus_SHIPMENT_STATUS_OUT_FOR_DELIVERY ShipmentStatus = 4
	ShipmentStatus_SHIPMENT_STATUS_DELIVERED        ShipmentStatus = 5
	ShipmentStatus_SHIPMENT_STATUS_FAILED_DELIVERY  ShipmentStatus = 6
	ShipmentStatus_SHIPMENT_STATUS_RETURNED         ShipmentStatus = 7
)

// Enum value maps for ShipmentStatus.
var (
	ShipmentStatus_name = map[int32]string{
		0: "SHIPMENT_STATUS_UNSPECIFIED",
		1: "SHIPMENT_STATUS_CREATED",
		2: "SHIPMENT_STATUS_PICKED_UP",
		3: "SHIPMENT_STATUS_IN_TRANSIT",
		4: "SHIPMENT_STATUS_OUT_FOR_DELIVERY",
		5: "SHIPMENT_STATUS_DELIVERED",
		6: "SHIPMENT_STATUS_FAILED_DELIVERY",
		7: "SHIPMENT_STATUS_RETURNED",
	}
	ShipmentStatus_value = map[string]int32{
		"SHIPMENT_STATUS_UNSPECIFIED":      0,
		"SHIPMENT_STATUS_CREATED":          1,
		"SHIPMENT_STATUS_PICKED_UP":        2,
		"SHIPMENT_STATUS_IN_TRANSIT":       3,
		"SHIPMENT_STATUS_OUT_FOR_DELIVERY": 4,
		"SHIPMENT_STATUS_DELIVERED":        5,
		"SHIPMENT_STATUS_FAILED_DELIVERY":  6,
		"SHIPMENT_STATUS_RETURNED":         7,
	}
)

func (x ShipmentStatus) Enum() *ShipmentStatus {
	p := new(ShipmentStatus)
	*p = x
	return p
}

func (x ShipmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_logistic_proto_enumTypes[0].Descriptor()
}

func (ShipmentStatus) Type() protoreflect.EnumType {
	return &file_protos_logistic_proto_enumTypes[0]
}

func (x ShipmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentStatus.Descriptor instead.
func (ShipmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{0}
}

type ShippingRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RateId        string                 `protobuf:"bytes,1,opt,name=rate_id,json=rateId,proto3" json:"rate_id,omitempty"`
	Carrier       string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	ServiceType   string                 `protobuf:"bytes,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Cost          float64                `protobuf:"fixed64,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	EstimatedDays int32                  `protobuf:"varint,6,opt,name=estimated_days,json=estimatedDays,proto3" json:"estimated_days,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingRate) Reset() {
	*x = ShippingRate{}
	mi := &file_protos_logistic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRate) ProtoMessage() {}

func (x *ShippingRate) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRate.ProtoReflect.Descriptor instead.
func (*ShippingRate) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingRate) GetRateId() string {
	if x != nil {
		return x.RateId
	}
	return ""
}

func (x *ShippingRate) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *ShippingRate) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ShippingRate) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShippingRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ShippingRate) GetEstimatedDays() int32 {
	if x != nil {
		return x.EstimatedDays
	}
	return 0
}

func (x *ShippingRate) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Shipment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId        string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TenantContext     *TenantContext         `protobuf:"bytes,2,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	OrderId           string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Carrier           string                 `protobuf:"bytes,4,opt,name=carrier,proto3" json:"carrier,omitempty"`
	TrackingNumber    string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status            ShipmentStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=logistic.ShipmentStatus" json:"status,omitempty"`
	FromAddress       *Address               `protobuf:"bytes,7,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress         *Address               `protobuf:"bytes,8,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Items             []*ShipmentItem        `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
	Dimensions        *ShipmentDimensions    `protobuf:"bytes,10,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Weight            float64                `protobuf:"fixed64,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Cost              float64                `protobuf:"fixed64,12,opt,name=cost,proto3" json:"cost,omitempty"`
	LabelUrl          string                 `protobuf:"bytes,13,opt,name=label_url,json=labelUrl,proto3" json:"label_url,omitempty"`
	TrackingEvents    []*TrackingEvent       `protobuf:"bytes,14,rep,name=tracking_events,json=trackingEvents,proto3" json:"tracking_events,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EstimatedDelivery *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=estimated_delivery,json=estimatedDelivery,proto3" json:"estimated_delivery,omitempty"`
	DeliveredAt       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_protos_logistic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{1}
}

func (x *Shipment) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *Shipment) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *Shipment) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Shipment) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *Shipment) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *Shipment) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *Shipment) GetFromAddress() *Address {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *Shipment) GetToAddress() *Address {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *Shipment) GetItems() []*ShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Shipment) GetDimensions() *ShipmentDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Shipment) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Shipment) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Shipment) GetLabelUrl() string {
	if x != nil {
		return x.LabelUrl
	}
	return ""
}

func (x *Shipment) GetTrackingEvents() []*TrackingEvent {
	if x != nil {
		return x.TrackingEvents
	}
	return nil
}

func (x *Shipment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Shipment) GetEstimatedDelivery() *timestamppb.Timestamp {
	if x != nil {
		return x.EstimatedDelivery
	}
	return nil
}

func (x *Shipment) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

type ShipmentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariantId     string                 `protobuf:"bytes,2,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Value         float64                `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentItem) Reset() {
	*x = ShipmentItem{}
	mi := &file_protos_logistic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentItem) ProtoMessage() {}

func (x *ShipmentItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentItem.ProtoReflect.Descriptor instead.
func (*ShipmentItem) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{2}
}

func (x *ShipmentItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ShipmentItem) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *ShipmentItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShipmentItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShipmentItem) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ShipmentDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        float64                `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,3,opt,name=height,proto3" json:"height,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"` // cm, in
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentDimensions) Reset() {
	*x = ShipmentDimensions{}
	mi := &file_protos_logistic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentDimensions) ProtoMessage() {}

func (x *ShipmentDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentDimensions.ProtoReflect.Descriptor instead.
func (*ShipmentDimensions) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentDimensions) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *ShipmentDimensions) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ShipmentDimensions) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ShipmentDimensions) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type TrackingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingEvent) Reset() {
	*x = TrackingEvent{}
	mi := &file_protos_logistic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingEvent) ProtoMessage() {}

func (x *TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingEvent.ProtoReflect.Descriptor instead.
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{4}
}

func (x *TrackingEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrackingEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrackingEvent) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrackingEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type LogisticsProvider struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProviderId        string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SupportedServices []string               `protobuf:"bytes,3,rep,name=supported_services,json=supportedServices,proto3" json:"supported_services,omitempty"`
	Configuration     map[string]string      `protobuf:"bytes,4,rep,name=configuration,proto3" json:"configuration,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsActive          bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogisticsProvider) Reset() {
	*x = LogisticsProvider{}
	mi := &file_protos_logistic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogisticsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogisticsProvider) ProtoMessage() {}

func (x *LogisticsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogisticsProvider.ProtoReflect.Descriptor instead.
func (*LogisticsProvider) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{5}
}

func (x *LogisticsProvider) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *LogisticsProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LogisticsProvider) GetSupportedServices() []string {
	if x != nil {
		return x.SupportedServices
	}
	return nil
}

func (x *LogisticsProvider) GetConfiguration() map[string]string {
	if x != nil {
		return x.Configuration
	}
	return nil
}

func (x *LogisticsProvider) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type GetShippingRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	FromAddress   *Address               `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     *Address               `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Items         []*ShipmentItem        `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Dimensions    *ShipmentDimensions    `protobuf:"bytes,5,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShippingRatesRequest) Reset() {
	*x = GetShippingRatesRequest{}
	mi := &file_protos_logistic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShippingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingRatesRequest) ProtoMessage() {}

func (x *GetShippingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetShippingRatesRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{6}
}

func (x *GetShippingRatesRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *GetShippingRatesRequest) GetFromAddress() *Address {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *GetShippingRatesRequest) GetToAddress() *Address {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *GetShippingRatesRequest) GetItems() []*ShipmentItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetShippingRatesRequest) GetDimensions() *ShipmentDimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *GetShippingRatesRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type GetShippingRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*ShippingRate        `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShippingRatesResponse) Reset() {
	*x = GetShippingRatesResponse{}
	mi := &file_protos_logistic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShippingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShippingRatesResponse) ProtoMessage() {}

func (x *GetShippingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShippingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetShippingRatesResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{7}
}

func (x *GetShippingRatesResponse) GetRates() []*ShippingRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *GetShippingRatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetShippingRatesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	Shipment      *Shipment              `protobuf:"bytes,2,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_protos_logistic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{8}
}

func (x *CreateShipmentRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *CreateShipmentRequest) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_protos_logistic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{9}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *CreateShipmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TrackShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackShipmentRequest) Reset() {
	*x = TrackShipmentRequest{}
	mi := &file_protos_logistic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentRequest) ProtoMessage() {}

func (x *TrackShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentRequest.ProtoReflect.Descriptor instead.
func (*TrackShipmentRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{10}
}

func (x *TrackShipmentRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *TrackShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type TrackShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackShipmentResponse) Reset() {
	*x = TrackShipmentResponse{}
	mi := &file_protos_logistic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentResponse) ProtoMessage() {}

func (x *TrackShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentResponse.ProtoReflect.Descriptor instead.
func (*TrackShipmentResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{11}
}

func (x *TrackShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *TrackShipmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrackShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateShipmentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        ShipmentStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=logistic.ShipmentStatus" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentStatusRequest) Reset() {
	*x = UpdateShipmentStatusRequest{}
	mi := &file_protos_logistic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusRequest) ProtoMessage() {}

func (x *UpdateShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateShipmentStatusRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *UpdateShipmentStatusRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetStatus() ShipmentStatus {
	if x != nil {
		return x.Status
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *UpdateShipmentStatusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type UpdateShipmentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateShipmentStatusResponse) Reset() {
	*x = UpdateShipmentStatusResponse{}
	mi := &file_protos_logistic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusResponse) ProtoMessage() {}

func (x *UpdateShipmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateShipmentStatusResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *UpdateShipmentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateShipmentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListShipmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	Pagination    *PageRequest           `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	StatusFilter  ShipmentStatus         `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=logistic.ShipmentStatus" json:"status_filter,omitempty"`
	Carrier       string                 `protobuf:"bytes,5,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipmentsRequest) Reset() {
	*x = ListShipmentsRequest{}
	mi := &file_protos_logistic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipmentsRequest) ProtoMessage() {}

func (x *ListShipmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipmentsRequest.ProtoReflect.Descriptor instead.
func (*ListShipmentsRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{14}
}

func (x *ListShipmentsRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *ListShipmentsRequest) GetPagination() *PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListShipmentsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ListShipmentsRequest) GetStatusFilter() ShipmentStatus {
	if x != nil {
		return x.StatusFilter
	}
	return ShipmentStatus_SHIPMENT_STATUS_UNSPECIFIED
}

func (x *ListShipmentsRequest) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

type ListShipmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipments     []*Shipment            `protobuf:"bytes,1,rep,name=shipments,proto3" json:"shipments,omitempty"`
	Pagination    *PageResponse          `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShipmentsResponse) Reset() {
	*x = ListShipmentsResponse{}
	mi := &file_protos_logistic_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShipmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShipmentsResponse) ProtoMessage() {}

func (x *ListShipmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShipmentsResponse.ProtoReflect.Descriptor instead.
func (*ListShipmentsResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{15}
}

func (x *ListShipmentsResponse) GetShipments() []*Shipment {
	if x != nil {
		return x.Shipments
	}
	return nil
}

func (x *ListShipmentsResponse) GetPagination() *PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListShipmentsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListShipmentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfigureLogisticsProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	Provider      *LogisticsProvider     `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureLogisticsProviderRequest) Reset() {
	*x = ConfigureLogisticsProviderRequest{}
	mi := &file_protos_logistic_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureLogisticsProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureLogisticsProviderRequest) ProtoMessage() {}

func (x *ConfigureLogisticsProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureLogisticsProviderRequest.ProtoReflect.Descriptor instead.
func (*ConfigureLogisticsProviderRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigureLogisticsProviderRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *ConfigureLogisticsProviderRequest) GetProvider() *LogisticsProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ConfigureLogisticsProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *LogisticsProvider     `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureLogisticsProviderResponse) Reset() {
	*x = ConfigureLogisticsProviderResponse{}
	mi := &file_protos_logistic_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureLogisticsProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureLogisticsProviderResponse) ProtoMessage() {}

func (x *ConfigureLogisticsProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureLogisticsProviderResponse.ProtoReflect.Descriptor instead.
func (*ConfigureLogisticsProviderResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigureLogisticsProviderResponse) GetProvider() *LogisticsProvider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ConfigureLogisticsProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureLogisticsProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateReturnLabelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantContext *TenantContext         `protobuf:"bytes,1,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"`
	ShipmentId    string                 `protobuf:"bytes,2,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReturnLabelRequest) Reset() {
	*x = CreateReturnLabelRequest{}
	mi := &file_protos_logistic_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReturnLabelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReturnLabelRequest) ProtoMessage() {}

func (x *CreateReturnLabelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReturnLabelRequest.ProtoReflect.Descriptor instead.
func (*CreateReturnLabelRequest) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{18}
}

func (x *CreateReturnLabelRequest) GetTenantContext() *TenantContext {
	if x != nil {
		return x.TenantContext
	}
	return nil
}

func (x *CreateReturnLabelRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *CreateReturnLabelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateReturnLabelResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LabelUrl       string                 `protobuf:"bytes,1,opt,name=label_url,json=labelUrl,proto3" json:"label_url,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReturnLabelResponse) Reset() {
	*x = CreateReturnLabelResponse{}
	mi := &file_protos_logistic_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReturnLabelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReturnLabelResponse) ProtoMessage() {}

func (x *CreateReturnLabelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_logistic_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReturnLabelResponse.ProtoReflect.Descriptor instead.
func (*CreateReturnLabelResponse) Descriptor() ([]byte, []int) {
	return file_protos_logistic_proto_rawDescGZIP(), []int{19}
}

func (x *CreateReturnLabelResponse) GetLabelUrl() string {
	if x != nil {
		return x.LabelUrl
	}
	return ""
}

func (x *CreateReturnLabelResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateReturnLabelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateReturnLabelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protos_logistic_proto protoreflect.FileDescriptor

const file_protos_logistic_proto_rawDesc = "" +
	"\n" +
	"\x15protos/logistic.proto\x12\blogistic\x1a\x12protos/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xba\x02\n" +
	"\fShippingRate\x12\x17\n" +
	"\arate_id\x18\x01 \x01(\tR\x06rateId\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier\x12!\n" +
	"\fservice_type\x18\x03 \x01(\tR\vserviceType\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x01R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12%\n" +
	"\x0eestimated_days\x18\x06 \x01(\x05R\restimatedDays\x12@\n" +
	"\bmetadata\x18\a \x03(\v2$.logistic.ShippingRate.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x06\n" +
	"\bShipment\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12;\n" +
	"\x0etenant_context\x18\x02 \x01(\v2\x14.types.TenantContextR\rtenantContext\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12\x18\n" +
	"\acarrier\x18\x04 \x01(\tR\acarrier\x12'\n" +
	"\x0ftracking_number\x18\x05 \x01(\tR\x0etrackingNumber\x120\n" +
	"\x06status\x18\x06 \x01(\x0e2\x18.logistic.ShipmentStatusR\x06status\x121\n" +
	"\ffrom_address\x18\a \x01(\v2\x0e.types.AddressR\vfromAddress\x12-\n" +
	"\n" +
	"to_address\x18\b \x01(\v2\x0e.types.AddressR\ttoAddress\x12,\n" +
	"\x05items\x18\t \x03(\v2\x16.logistic.ShipmentItemR\x05items\x12<\n" +
	"\n" +
	"dimensions\x18\n" +
	" \x01(\v2\x1c.logistic.ShipmentDimensionsR\n" +
	"dimensions\x12\x16\n" +
	"\x06weight\x18\v \x01(\x01R\x06weight\x12\x12\n" +
	"\x04cost\x18\f \x01(\x01R\x04cost\x12\x1b\n" +
	"\tlabel_url\x18\r \x01(\tR\blabelUrl\x12@\n" +
	"\x0ftracking_events\x18\x0e \x03(\v2\x17.logistic.TrackingEventR\x0etrackingEvents\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12I\n" +
	"\x12estimated_delivery\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x11estimatedDelivery\x12=\n" +
	"\fdelivered_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\"\xa0\x01\n" +
	"\fShipmentItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x02 \x01(\tR\tvariantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\"n\n" +
	"\x12ShipmentDimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x01R\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x01R\x06height\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\"\x9f\x01\n" +
	"\rTrackingEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xac\x02\n" +
	"\x11LogisticsProvider\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x12supported_services\x18\x03 \x03(\tR\x11supportedServices\x12T\n" +
	"\rconfiguration\x18\x04 \x03(\v2..logistic.LogisticsProvider.ConfigurationEntryR\rconfiguration\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x1a@\n" +
	"\x12ConfigurationEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x17GetShippingRatesRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x121\n" +
	"\ffrom_address\x18\x02 \x01(\v2\x0e.types.AddressR\vfromAddress\x12-\n" +
	"\n" +
	"to_address\x18\x03 \x01(\v2\x0e.types.AddressR\ttoAddress\x12,\n" +
	"\x05items\x18\x04 \x03(\v2\x16.logistic.ShipmentItemR\x05items\x12<\n" +
	"\n" +
	"dimensions\x18\x05 \x01(\v2\x1c.logistic.ShipmentDimensionsR\n" +
	"dimensions\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\"|\n" +
	"\x18GetShippingRatesResponse\x12,\n" +
	"\x05rates\x18\x01 \x03(\v2\x16.logistic.ShippingRateR\x05rates\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x84\x01\n" +
	"\x15CreateShipmentRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x12.\n" +
	"\bshipment\x18\x02 \x01(\v2\x12.logistic.ShipmentR\bshipment\"|\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.logistic.ShipmentR\bshipment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\x14TrackShipmentRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\"{\n" +
	"\x15TrackShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.logistic.ShipmentR\bshipment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xdf\x01\n" +
	"\x1bUpdateShipmentStatusRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x120\n" +
	"\x06status\x18\x03 \x01(\x0e2\x18.logistic.ShipmentStatusR\x06status\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\x82\x01\n" +
	"\x1cUpdateShipmentStatusResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.logistic.ShipmentR\bshipment\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfb\x01\n" +
	"\x14ListShipmentsRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x122\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x12.types.PageRequestR\n" +
	"pagination\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\x12=\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x18.logistic.ShipmentStatusR\fstatusFilter\x12\x18\n" +
	"\acarrier\x18\x05 \x01(\tR\acarrier\"\xb2\x01\n" +
	"\x15ListShipmentsResponse\x120\n" +
	"\tshipments\x18\x01 \x03(\v2\x12.logistic.ShipmentR\tshipments\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.types.PageResponseR\n" +
	"pagination\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x99\x01\n" +
	"!ConfigureLogisticsProviderRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x127\n" +
	"\bprovider\x18\x02 \x01(\v2\x1b.logistic.LogisticsProviderR\bprovider\"\x91\x01\n" +
	"\"ConfigureLogisticsProviderResponse\x127\n" +
	"\bprovider\x18\x01 \x01(\v2\x1b.logistic.LogisticsProviderR\bprovider\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x01\n" +
	"\x18CreateReturnLabelRequest\x12;\n" +
	"\x0etenant_context\x18\x01 \x01(\v2\x14.types.TenantContextR\rtenantContext\x12\x1f\n" +
	"\vshipment_id\x18\x02 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x95\x01\n" +
	"\x19CreateReturnLabelResponse\x12\x1b\n" +
	"\tlabel_url\x18\x01 \x01(\tR\blabelUrl\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*\x95\x02\n" +
	"\x0eShipmentStatus\x12\x1f\n" +
	"\x1bSHIPMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SHIPMENT_STATUS_CREATED\x10\x01\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_PICKED_UP\x10\x02\x12\x1e\n" +
	"\x1aSHIPMENT_STATUS_IN_TRANSIT\x10\x03\x12$\n" +
	" SHIPMENT_STATUS_OUT_FOR_DELIVERY\x10\x04\x12\x1d\n" +
	"\x19SHIPMENT_STATUS_DELIVERED\x10\x05\x12#\n" +
	"\x1fSHIPMENT_STATUS_FAILED_DELIVERY\x10\x06\x12\x1c\n" +
	"\x18SHIPMENT_STATUS_RETURNED\x10\a2\xa4\x05\n" +
	"\x10LogisticsService\x12Y\n" +
	"\x10GetShippingRates\x12!.logistic.GetShippingRatesRequest\x1a\".logistic.GetShippingRatesResponse\x12S\n" +
	"\x0eCreateShipment\x12\x1f.logistic.CreateShipmentRequest\x1a .logistic.CreateShipmentResponse\x12P\n" +
	"\rTrackShipment\x12\x1e.logistic.TrackShipmentRequest\x1a\x1f.logistic.TrackShipmentResponse\x12e\n" +
	"\x14UpdateShipmentStatus\x12%.logistic.UpdateShipmentStatusRequest\x1a&.logistic.UpdateShipmentStatusResponse\x12P\n" +
	"\rListShipments\x12\x1e.logistic.ListShipmentsRequest\x1a\x1f.logistic.ListShipmentsResponse\x12w\n" +
	"\x1aConfigureLogisticsProvider\x12+.logistic.ConfigureLogisticsProviderRequest\x1a,.logistic.ConfigureLogisticsProviderResponse\x12\\\n" +
	"\x11CreateReturnLabel\x12\".logistic.CreateReturnLabelRequest\x1a#.logistic.CreateReturnLabelResponseB2Z0github.com/mainheartng/marketa_api/protos;protosb\x06proto3"

var (
	file_protos_logistic_proto_rawDescOnce sync.Once
	file_protos_logistic_proto_rawDescData []byte
)

func file_protos_logistic_proto_rawDescGZIP() []byte {
	file_protos_logistic_proto_rawDescOnce.Do(func() {
		file_protos_logistic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_logistic_proto_rawDesc), len(file_protos_logistic_proto_rawDesc)))
	})
	return file_protos_logistic_proto_rawDescData
}

var file_protos_logistic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_logistic_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_protos_logistic_proto_goTypes = []any{
	(ShipmentStatus)(0),                        // 0: logistic.ShipmentStatus
	(*ShippingRate)(nil),                       // 1: logistic.ShippingRate
	(*Shipment)(nil),                           // 2: logistic.Shipment
	(*ShipmentItem)(nil),                       // 3: logistic.ShipmentItem
	(*ShipmentDimensions)(nil),                 // 4: logistic.ShipmentDimensions
	(*TrackingEvent)(nil),                      // 5: logistic.TrackingEvent
	(*LogisticsProvider)(nil),                  // 6: logistic.LogisticsProvider
	(*GetShippingRatesRequest)(nil),            // 7: logistic.GetShippingRatesRequest
	(*GetShippingRatesResponse)(nil),           // 8: logistic.GetShippingRatesResponse
	(*CreateShipmentRequest)(nil),              // 9: logistic.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),             // 10: logistic.CreateShipmentResponse
	(*TrackShipmentRequest)(nil),               // 11: logistic.TrackShipmentRequest
	(*TrackShipmentResponse)(nil),              // 12: logistic.TrackShipmentResponse
	(*UpdateShipmentStatusRequest)(nil),        // 13: logistic.UpdateShipmentStatusRequest
	(*UpdateShipmentStatusResponse)(nil),       // 14: logistic.UpdateShipmentStatusResponse
	(*ListShipmentsRequest)(nil),               // 15: logistic.ListShipmentsRequest
	(*ListShipmentsResponse)(nil),              // 16: logistic.ListShipmentsResponse
	(*ConfigureLogisticsProviderRequest)(nil),  // 17: logistic.ConfigureLogisticsProviderRequest
	(*ConfigureLogisticsProviderResponse)(nil), // 18: logistic.ConfigureLogisticsProviderResponse
	(*CreateReturnLabelRequest)(nil),           // 19: logistic.CreateReturnLabelRequest
	(*CreateReturnLabelResponse)(nil),          // 20: logistic.CreateReturnLabelResponse
	nil,                                        // 21: logistic.ShippingRate.MetadataEntry
	nil,                                        // 22: logistic.LogisticsProvider.ConfigurationEntry
	(*TenantContext)(nil),                      // 23: types.TenantContext
	(*Address)(nil),                            // 24: types.Address
	(*timestamppb.Timestamp)(nil),              // 25: google.protobuf.Timestamp
	(*PageRequest)(nil),                        // 26: types.PageRequest
	(*PageResponse)(nil),                       // 27: types.PageResponse
}
var file_protos_logistic_proto_depIdxs = []int32{
	21, // 0: logistic.ShippingRate.metadata:type_name -> logistic.ShippingRate.MetadataEntry
	23, // 1: logistic.Shipment.tenant_context:type_name -> types.TenantContext
	0,  // 2: logistic.Shipment.status:type_name -> logistic.ShipmentStatus
	24, // 3: logistic.Shipment.from_address:type_name -> types.Address
	24, // 4: logistic.Shipment.to_address:type_name -> types.Address
	3,  // 5: logistic.Shipment.items:type_name -> logistic.ShipmentItem
	4,  // 6: logistic.Shipment.dimensions:type_name -> logistic.ShipmentDimensions
	5,  // 7: logistic.Shipment.tracking_events:type_name -> logistic.TrackingEvent
	25, // 8: logistic.Shipment.created_at:type_name -> google.protobuf.Timestamp
	25, // 9: logistic.Shipment.estimated_delivery:type_name -> google.protobuf.Timestamp
	25, // 10: logistic.Shipment.delivered_at:type_name -> google.protobuf.Timestamp
	25, // 11: logistic.TrackingEvent.timestamp:type_name -> google.protobuf.Timestamp
	22, // 12: logistic.LogisticsProvider.configuration:type_name -> logistic.LogisticsProvider.ConfigurationEntry
	23, // 13: logistic.GetShippingRatesRequest.tenant_context:type_name -> types.TenantContext
	24, // 14: logistic.GetShippingRatesRequest.from_address:type_name -> types.Address
	24, // 15: logistic.GetShippingRatesRequest.to_address:type_name -> types.Address
	3,  // 16: logistic.GetShippingRatesRequest.items:type_name -> logistic.ShipmentItem
	4,  // 17: logistic.GetShippingRatesRequest.dimensions:type_name -> logistic.ShipmentDimensions
	1,  // 18: logistic.GetShippingRatesResponse.rates:type_name -> logistic.ShippingRate
	23, // 19: logistic.CreateShipmentRequest.tenant_context:type_name -> types.TenantContext
	2,  // 20: logistic.CreateShipmentRequest.shipment:type_name -> logistic.Shipment
	2,  // 21: logistic.CreateShipmentResponse.shipment:type_name -> logistic.Shipment
	23, // 22: logistic.TrackShipmentRequest.tenant_context:type_name -> types.TenantContext
	2,  // 23: logistic.TrackShipmentResponse.shipment:type_name -> logistic.Shipment
	23, // 24: logistic.UpdateShipmentStatusRequest.tenant_context:type_name -> types.TenantContext
	0,  // 25: logistic.UpdateShipmentStatusRequest.status:type_name -> logistic.ShipmentStatus
	2,  // 26: logistic.UpdateShipmentStatusResponse.shipment:type_name -> logistic.Shipment
	23, // 27: logistic.ListShipmentsRequest.tenant_context:type_name -> types.TenantContext
	26, // 28: logistic.ListShipmentsRequest.pagination:type_name -> types.PageRequest
	0,  // 29: logistic.ListShipmentsRequest.status_filter:type_name -> logistic.ShipmentStatus
	2,  // 30: logistic.ListShipmentsResponse.shipments:type_name -> logistic.Shipment
	27, // 31: logistic.ListShipmentsResponse.pagination:type_name -> types.PageResponse
	23, // 32: logistic.ConfigureLogisticsProviderRequest.tenant_context:type_name -> types.TenantContext
	6,  // 33: logistic.ConfigureLogisticsProviderRequest.provider:type_name -> logistic.LogisticsProvider
	6,  // 34: logistic.ConfigureLogisticsProviderResponse.provider:type_name -> logistic.LogisticsProvider
	23, // 35: logistic.CreateReturnLabelRequest.tenant_context:type_name -> types.TenantContext
	7,  // 36: logistic.LogisticsService.GetShippingRates:input_type -> logistic.GetShippingRatesRequest
	9,  // 37: logistic.LogisticsService.CreateShipment:input_type -> logistic.CreateShipmentRequest
	11, // 38: logistic.LogisticsService.TrackShipment:input_type -> logistic.TrackShipmentRequest
	13, // 39: logistic.LogisticsService.UpdateShipmentStatus:input_type -> logistic.UpdateShipmentStatusRequest
	15, // 40: logistic.LogisticsService.ListShipments:input_type -> logistic.ListShipmentsRequest
	17, // 41: logistic.LogisticsService.ConfigureLogisticsProvider:input_type -> logistic.ConfigureLogisticsProviderRequest
	19, // 42: logistic.LogisticsService.CreateReturnLabel:input_type -> logistic.CreateReturnLabelRequest
	8,  // 43: logistic.LogisticsService.GetShippingRates:output_type -> logistic.GetShippingRatesResponse
	10, // 44: logistic.LogisticsService.CreateShipment:output_type -> logistic.CreateShipmentResponse
	12, // 45: logistic.LogisticsService.TrackShipment:output_type -> logistic.TrackShipmentResponse
	14, // 46: logistic.LogisticsService.UpdateShipmentStatus:output_type -> logistic.UpdateShipmentStatusResponse
	16, // 47: logistic.LogisticsService.ListShipments:output_type -> logistic.ListShipmentsResponse
	18, // 48: logistic.LogisticsService.ConfigureLogisticsProvider:output_type -> logistic.ConfigureLogisticsProviderResponse
	20, // 49: logistic.LogisticsService.CreateReturnLabel:output_type -> logistic.CreateReturnLabelResponse
	43, // [43:50] is the sub-list for method output_type
	36, // [36:43] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_protos_logistic_proto_init() }
func file_protos_logistic_proto_init() {
	if File_protos_logistic_proto != nil {
		return
	}
	file_protos_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_logistic_proto_rawDesc), len(file_protos_logistic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_logistic_proto_goTypes,
		DependencyIndexes: file_protos_logistic_proto_depIdxs,
		EnumInfos:         file_protos_logistic_proto_enumTypes,
		MessageInfos:      file_protos_logistic_proto_msgTypes,
	}.Build()
	File_protos_logistic_proto = out.File
	file_protos_logistic_proto_goTypes = nil
	file_protos_logistic_proto_depIdxs = nil
}
