// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protos/types.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationType int32

const (
	OrganizationType_business_name OrganizationType = 0
)

// Enum value maps for OrganizationType.
var (
	OrganizationType_name = map[int32]string{
		0: "business_name",
	}
	OrganizationType_value = map[string]int32{
		"business_name": 0,
	}
)

func (x OrganizationType) Enum() *OrganizationType {
	p := new(OrganizationType)
	*p = x
	return p
}

func (x OrganizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrganizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[0].Descriptor()
}

func (OrganizationType) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[0]
}

func (x OrganizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrganizationType.Descriptor instead.
func (OrganizationType) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{0}
}

type AdminLevel int32

const (
	AdminLevel_owner       AdminLevel = 0
	AdminLevel_admin       AdminLevel = 1
	AdminLevel_viewer      AdminLevel = 2
	AdminLevel_super_admin AdminLevel = 3
)

// Enum value maps for AdminLevel.
var (
	AdminLevel_name = map[int32]string{
		0: "owner",
		1: "admin",
		2: "viewer",
		3: "super_admin",
	}
	AdminLevel_value = map[string]int32{
		"owner":       0,
		"admin":       1,
		"viewer":      2,
		"super_admin": 3,
	}
)

func (x AdminLevel) Enum() *AdminLevel {
	p := new(AdminLevel)
	*p = x
	return p
}

func (x AdminLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[1].Descriptor()
}

func (AdminLevel) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[1]
}

func (x AdminLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminLevel.Descriptor instead.
func (AdminLevel) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{1}
}

type InviteStatus int32

const (
	InviteStatus_pending   InviteStatus = 0
	InviteStatus_rejected  InviteStatus = 1
	InviteStatus_cancelled InviteStatus = 2
	InviteStatus_accepted  InviteStatus = 3
)

// Enum value maps for InviteStatus.
var (
	InviteStatus_name = map[int32]string{
		0: "pending",
		1: "rejected",
		2: "cancelled",
		3: "accepted",
	}
	InviteStatus_value = map[string]int32{
		"pending":   0,
		"rejected":  1,
		"cancelled": 2,
		"accepted":  3,
	}
)

func (x InviteStatus) Enum() *InviteStatus {
	p := new(InviteStatus)
	*p = x
	return p
}

func (x InviteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[2].Descriptor()
}

func (InviteStatus) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[2]
}

func (x InviteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteStatus.Descriptor instead.
func (InviteStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{2}
}

type IntegrationTypes int32

const (
	IntegrationTypes_payment   IntegrationTypes = 0
	IntegrationTypes_logistic  IntegrationTypes = 1
	IntegrationTypes_que       IntegrationTypes = 2
	IntegrationTypes_template  IntegrationTypes = 3
	IntegrationTypes_component IntegrationTypes = 4
)

// Enum value maps for IntegrationTypes.
var (
	IntegrationTypes_name = map[int32]string{
		0: "payment",
		1: "logistic",
		2: "que",
		3: "template",
		4: "component",
	}
	IntegrationTypes_value = map[string]int32{
		"payment":   0,
		"logistic":  1,
		"que":       2,
		"template":  3,
		"component": 4,
	}
)

func (x IntegrationTypes) Enum() *IntegrationTypes {
	p := new(IntegrationTypes)
	*p = x
	return p
}

func (x IntegrationTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[3].Descriptor()
}

func (IntegrationTypes) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[3]
}

func (x IntegrationTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationTypes.Descriptor instead.
func (IntegrationTypes) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{3}
}

// Common status enum
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
	Status_STATUS_PENDING     Status = 3
	Status_STATUS_SUSPENDED   Status = 4
	Status_STATUS_DELETED     Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_PENDING",
		4: "STATUS_SUSPENDED",
		5: "STATUS_DELETED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
		"STATUS_PENDING":     3,
		"STATUS_SUSPENDED":   4,
		"STATUS_DELETED":     5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_types_proto_enumTypes[4].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_types_proto_enumTypes[4]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{4}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=types.Status" json:"status,omitempty"`
	Roles         []*UserRole            `protobuf:"bytes,8,rep,name=roles,proto3" json:"roles,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,9,opt,name=profile,proto3" json:"profile,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *User) GetRoles() []*UserRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UserRole struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	RoleName       string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	Permissions    []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_protos_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{1}
}

func (x *UserRole) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UserRole) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	CustomFields  map[string]string      `protobuf:"bytes,3,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_protos_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserProfile) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserProfile) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

type Organization struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status         Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=types.Status" json:"status,omitempty"`
	Settings       *OrganizationSettings  `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	Type           OrganizationType       `protobuf:"varint,7,opt,name=type,proto3,enum=types.OrganizationType" json:"type,omitempty"`
	Staff          []*Staff               `protobuf:"bytes,8,rep,name=staff,proto3" json:"staff,omitempty"`
	Projects       []*Project             `protobuf:"bytes,9,rep,name=projects,proto3" json:"projects,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_protos_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{3}
}

func (x *Organization) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Organization) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Organization) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Organization) GetSettings() *OrganizationSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Organization) GetType() OrganizationType {
	if x != nil {
		return x.Type
	}
	return OrganizationType_business_name
}

func (x *Organization) GetStaff() []*Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *Organization) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Organization) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Organization) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type OrganizationSettings struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AllowMultiMembership bool                   `protobuf:"varint,1,opt,name=allow_multi_membership,json=allowMultiMembership,proto3" json:"allow_multi_membership,omitempty"`
	CustomSettings       map[string]string      `protobuf:"bytes,2,rep,name=custom_settings,json=customSettings,proto3" json:"custom_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OrganizationSettings) Reset() {
	*x = OrganizationSettings{}
	mi := &file_protos_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSettings) ProtoMessage() {}

func (x *OrganizationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationSettings.ProtoReflect.Descriptor instead.
func (*OrganizationSettings) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationSettings) GetAllowMultiMembership() bool {
	if x != nil {
		return x.AllowMultiMembership
	}
	return false
}

func (x *OrganizationSettings) GetCustomSettings() map[string]string {
	if x != nil {
		return x.CustomSettings
	}
	return nil
}

type Staff struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User           *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Level          AdminLevel             `protobuf:"varint,5,opt,name=level,proto3,enum=types.AdminLevel" json:"level,omitempty"`
	Status         Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=types.Status" json:"status,omitempty"`
	Invite         InviteStatus           `protobuf:"varint,7,opt,name=invite,proto3,enum=types.InviteStatus" json:"invite,omitempty"`
	OrganizationId string                 `protobuf:"bytes,8,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Organization   *Organization          `protobuf:"bytes,9,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_protos_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{5}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Staff) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Staff) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Staff) GetLevel() AdminLevel {
	if x != nil {
		return x.Level
	}
	return AdminLevel_owner
}

func (x *Staff) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Staff) GetInvite() InviteStatus {
	if x != nil {
		return x.Invite
	}
	return InviteStatus_pending
}

func (x *Staff) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Staff) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=types.Status" json:"status,omitempty"`
	Integrations  []*ProjectIntegrations `protobuf:"bytes,6,rep,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_protos_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{6}
}

func (x *Project) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Project) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Project) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Project) GetIntegrations() []*ProjectIntegrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

type Integrations struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IntegrationType IntegrationTypes       `protobuf:"varint,4,opt,name=integration_type,json=integrationType,proto3,enum=types.IntegrationTypes" json:"integration_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Integrations) Reset() {
	*x = Integrations{}
	mi := &file_protos_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integrations) ProtoMessage() {}

func (x *Integrations) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integrations.ProtoReflect.Descriptor instead.
func (*Integrations) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{7}
}

func (x *Integrations) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Integrations) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Integrations) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Integrations) GetIntegrationType() IntegrationTypes {
	if x != nil {
		return x.IntegrationType
	}
	return IntegrationTypes_payment
}

type ProjectIntegrations struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ProjectId      string                 `protobuf:"bytes,3,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Project        *Project               `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	IntegrationsId string                 `protobuf:"bytes,5,opt,name=integrations_id,json=integrationsId,proto3" json:"integrations_id,omitempty"`
	Integrations   *Integrations          `protobuf:"bytes,6,opt,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectIntegrations) Reset() {
	*x = ProjectIntegrations{}
	mi := &file_protos_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectIntegrations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectIntegrations) ProtoMessage() {}

func (x *ProjectIntegrations) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectIntegrations.ProtoReflect.Descriptor instead.
func (*ProjectIntegrations) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectIntegrations) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectIntegrations) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProjectIntegrations) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ProjectIntegrations) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectIntegrations) GetIntegrationsId() string {
	if x != nil {
		return x.IntegrationsId
	}
	return ""
}

func (x *ProjectIntegrations) GetIntegrations() *Integrations {
	if x != nil {
		return x.Integrations
	}
	return nil
}

// Multi-tenancy context - included in all requests
type TenantContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRoles      []string               `protobuf:"bytes,4,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TenantContext) Reset() {
	*x = TenantContext{}
	mi := &file_protos_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantContext) ProtoMessage() {}

func (x *TenantContext) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantContext.ProtoReflect.Descriptor instead.
func (*TenantContext) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{9}
}

func (x *TenantContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantContext) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TenantContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TenantContext) GetUserRoles() []string {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *TenantContext) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Common pagination
type PageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"` // ASC, DESC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageRequest) Reset() {
	*x = PageRequest{}
	mi := &file_protos_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageRequest) ProtoMessage() {}

func (x *PageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageRequest.ProtoReflect.Descriptor instead.
func (*PageRequest) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{10}
}

func (x *PageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *PageRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type PageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalCount    int32                  `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageResponse) Reset() {
	*x = PageResponse{}
	mi := &file_protos_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageResponse) ProtoMessage() {}

func (x *PageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageResponse.ProtoReflect.Descriptor instead.
func (*PageResponse) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{11}
}

func (x *PageResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PageResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Company       string                 `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	AddressLine_1 string                 `protobuf:"bytes,5,opt,name=address_line_1,json=addressLine1,proto3" json:"address_line_1,omitempty"`
	AddressLine_2 string                 `protobuf:"bytes,6,opt,name=address_line_2,json=addressLine2,proto3" json:"address_line_2,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,10,opt,name=country,proto3" json:"country,omitempty"`
	Phone         string                 `protobuf:"bytes,11,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_protos_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_protos_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_protos_types_proto_rawDescGZIP(), []int{12}
}

func (x *Address) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Address) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Address) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Address) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Address) GetAddressLine_1() string {
	if x != nil {
		return x.AddressLine_1
	}
	return ""
}

func (x *Address) GetAddressLine_2() string {
	if x != nil {
		return x.AddressLine_2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_protos_types_proto protoreflect.FileDescriptor

const file_protos_types_proto_rawDesc = "" +
	"\n" +
	"\x12protos/types.proto\x12\x05types\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12%\n" +
	"\x06status\x18\a \x01(\x0e2\r.types.StatusR\x06status\x12%\n" +
	"\x05roles\x18\b \x03(\v2\x0f.types.UserRoleR\x05roles\x12,\n" +
	"\aprofile\x18\t \x01(\v2\x12.types.UserProfileR\aprofile\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\bUserRole\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\"\xd9\x01\n" +
	"\vUserProfile\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12(\n" +
	"\aaddress\x18\x02 \x01(\v2\x0e.types.AddressR\aaddress\x12I\n" +
	"\rcustom_fields\x18\x03 \x03(\v2$.types.UserProfile.CustomFieldsEntryR\fcustomFields\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x03\n" +
	"\fOrganization\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12%\n" +
	"\x06status\x18\x05 \x01(\x0e2\r.types.StatusR\x06status\x127\n" +
	"\bsettings\x18\x06 \x01(\v2\x1b.types.OrganizationSettingsR\bsettings\x12+\n" +
	"\x04type\x18\a \x01(\x0e2\x17.types.OrganizationTypeR\x04type\x12\"\n" +
	"\x05staff\x18\b \x03(\v2\f.types.StaffR\x05staff\x12*\n" +
	"\bprojects\x18\t \x03(\v2\x0e.types.ProjectR\bprojects\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe9\x01\n" +
	"\x14OrganizationSettings\x124\n" +
	"\x16allow_multi_membership\x18\x01 \x01(\bR\x14allowMultiMembership\x12X\n" +
	"\x0fcustom_settings\x18\x02 \x03(\v2/.types.OrganizationSettings.CustomSettingsEntryR\x0ecustomSettings\x1aA\n" +
	"\x13CustomSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\x05Staff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\x04user\x18\x03 \x01(\v2\v.types.UserR\x04user\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x12'\n" +
	"\x05level\x18\x05 \x01(\x0e2\x11.types.AdminLevelR\x05level\x12%\n" +
	"\x06status\x18\x06 \x01(\x0e2\r.types.StatusR\x06status\x12+\n" +
	"\x06invite\x18\a \x01(\x0e2\x13.types.InviteStatusR\x06invite\x12'\n" +
	"\x0forganization_id\x18\b \x01(\tR\x0eorganizationId\x127\n" +
	"\forganization\x18\t \x01(\v2\x13.types.OrganizationR\forganization\"\xd2\x01\n" +
	"\aProject\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x06status\x18\x05 \x01(\x0e2\r.types.StatusR\x06status\x12>\n" +
	"\fintegrations\x18\x06 \x03(\v2\x1a.types.ProjectIntegrationsR\fintegrations\"\xa0\x01\n" +
	"\fIntegrations\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12B\n" +
	"\x10integration_type\x18\x04 \x01(\x0e2\x17.types.IntegrationTypesR\x0fintegrationType\"\xef\x01\n" +
	"\x13ProjectIntegrations\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"project_id\x18\x03 \x01(\tR\tprojectId\x12(\n" +
	"\aproject\x18\x04 \x01(\v2\x0e.types.ProjectR\aproject\x12'\n" +
	"\x0fintegrations_id\x18\x05 \x01(\tR\x0eintegrationsId\x127\n" +
	"\fintegrations\x18\x06 \x01(\v2\x13.types.IntegrationsR\fintegrations\"\x8a\x02\n" +
	"\rTenantContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_roles\x18\x04 \x03(\tR\tuserRoles\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".types.TenantContext.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"v\n" +
	"\vPageRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"{\n" +
	"\fPageResponse\x12\x1f\n" +
	"\vtotal_count\x18\x01 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\"\xc5\x02\n" +
	"\aAddress\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x18\n" +
	"\acompany\x18\x04 \x01(\tR\acompany\x12$\n" +
	"\x0eaddress_line_1\x18\x05 \x01(\tR\faddressLine1\x12$\n" +
	"\x0eaddress_line_2\x18\x06 \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\n" +
	" \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\v \x01(\tR\x05phone*%\n" +
	"\x10OrganizationType\x12\x11\n" +
	"\rbusiness_name\x10\x00*?\n" +
	"\n" +
	"AdminLevel\x12\t\n" +
	"\x05owner\x10\x00\x12\t\n" +
	"\x05admin\x10\x01\x12\n" +
	"\n" +
	"\x06viewer\x10\x02\x12\x0f\n" +
	"\vsuper_admin\x10\x03*F\n" +
	"\fInviteStatus\x12\v\n" +
	"\apending\x10\x00\x12\f\n" +
	"\brejected\x10\x01\x12\r\n" +
	"\tcancelled\x10\x02\x12\f\n" +
	"\baccepted\x10\x03*S\n" +
	"\x10IntegrationTypes\x12\v\n" +
	"\apayment\x10\x00\x12\f\n" +
	"\blogistic\x10\x01\x12\a\n" +
	"\x03que\x10\x02\x12\f\n" +
	"\btemplate\x10\x03\x12\r\n" +
	"\tcomponent\x10\x04*\x86\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x03\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_DELETED\x10\x05B2Z0github.com/mainheartng/marketa_api/protos;protosb\x06proto3"

var (
	file_protos_types_proto_rawDescOnce sync.Once
	file_protos_types_proto_rawDescData []byte
)

func file_protos_types_proto_rawDescGZIP() []byte {
	file_protos_types_proto_rawDescOnce.Do(func() {
		file_protos_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_types_proto_rawDesc), len(file_protos_types_proto_rawDesc)))
	})
	return file_protos_types_proto_rawDescData
}

var file_protos_types_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_protos_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protos_types_proto_goTypes = []any{
	(OrganizationType)(0),         // 0: types.OrganizationType
	(AdminLevel)(0),               // 1: types.AdminLevel
	(InviteStatus)(0),             // 2: types.InviteStatus
	(IntegrationTypes)(0),         // 3: types.IntegrationTypes
	(Status)(0),                   // 4: types.Status
	(*User)(nil),                  // 5: types.User
	(*UserRole)(nil),              // 6: types.UserRole
	(*UserProfile)(nil),           // 7: types.UserProfile
	(*Organization)(nil),          // 8: types.Organization
	(*OrganizationSettings)(nil),  // 9: types.OrganizationSettings
	(*Staff)(nil),                 // 10: types.Staff
	(*Project)(nil),               // 11: types.Project
	(*Integrations)(nil),          // 12: types.Integrations
	(*ProjectIntegrations)(nil),   // 13: types.ProjectIntegrations
	(*TenantContext)(nil),         // 14: types.TenantContext
	(*PageRequest)(nil),           // 15: types.PageRequest
	(*PageResponse)(nil),          // 16: types.PageResponse
	(*Address)(nil),               // 17: types.Address
	nil,                           // 18: types.UserProfile.CustomFieldsEntry
	nil,                           // 19: types.OrganizationSettings.CustomSettingsEntry
	nil,                           // 20: types.TenantContext.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_protos_types_proto_depIdxs = []int32{
	4,  // 0: types.User.status:type_name -> types.Status
	6,  // 1: types.User.roles:type_name -> types.UserRole
	7,  // 2: types.User.profile:type_name -> types.UserProfile
	21, // 3: types.User.created_at:type_name -> google.protobuf.Timestamp
	21, // 4: types.User.updated_at:type_name -> google.protobuf.Timestamp
	17, // 5: types.UserProfile.address:type_name -> types.Address
	18, // 6: types.UserProfile.custom_fields:type_name -> types.UserProfile.CustomFieldsEntry
	4,  // 7: types.Organization.status:type_name -> types.Status
	9,  // 8: types.Organization.settings:type_name -> types.OrganizationSettings
	0,  // 9: types.Organization.type:type_name -> types.OrganizationType
	10, // 10: types.Organization.staff:type_name -> types.Staff
	11, // 11: types.Organization.projects:type_name -> types.Project
	21, // 12: types.Organization.created_at:type_name -> google.protobuf.Timestamp
	21, // 13: types.Organization.updated_at:type_name -> google.protobuf.Timestamp
	19, // 14: types.OrganizationSettings.custom_settings:type_name -> types.OrganizationSettings.CustomSettingsEntry
	5,  // 15: types.Staff.user:type_name -> types.User
	1,  // 16: types.Staff.level:type_name -> types.AdminLevel
	4,  // 17: types.Staff.status:type_name -> types.Status
	2,  // 18: types.Staff.invite:type_name -> types.InviteStatus
	8,  // 19: types.Staff.organization:type_name -> types.Organization
	4,  // 20: types.Project.status:type_name -> types.Status
	13, // 21: types.Project.integrations:type_name -> types.ProjectIntegrations
	3,  // 22: types.Integrations.integration_type:type_name -> types.IntegrationTypes
	11, // 23: types.ProjectIntegrations.project:type_name -> types.Project
	12, // 24: types.ProjectIntegrations.integrations:type_name -> types.Integrations
	20, // 25: types.TenantContext.metadata:type_name -> types.TenantContext.MetadataEntry
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_protos_types_proto_init() }
func file_protos_types_proto_init() {
	if File_protos_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_types_proto_rawDesc), len(file_protos_types_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_types_proto_goTypes,
		DependencyIndexes: file_protos_types_proto_depIdxs,
		EnumInfos:         file_protos_types_proto_enumTypes,
		MessageInfos:      file_protos_types_proto_msgTypes,
	}.Build()
	File_protos_types_proto = out.File
	file_protos_types_proto_goTypes = nil
	file_protos_types_proto_depIdxs = nil
}
